# Generated by Django 5.0.6 on 2024-06-13 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('scooty', 'Scooty'), ('gear-bike', 'Gear Bike'), ('ev', 'EV')], max_length=100)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_number', models.CharField(max_length=20)),
                ('imagefile', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('kilometers_driven', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='bikes.bike')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('host', 'Host'), ('user', 'User')], default='user', max_length=100)),
                ('age', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits.', regex='^\\d{4}\\s\\d{4}\\s\\d{4}$')])),
                ('driving_license', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid driving license number in the format "TS01 987654321098".', regex='^[A-Z]{2}\\d{2}\\s\\d{11}$')])),
                ('interested_bikes', models.ManyToManyField(related_name='interested_users', to='bikes.bike')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.users')),
            ],
        ),
    ]
